### PR TITLE
chore(tox): run tests against sqla 1.3 & 1.4

### PR DESCRIPTION
**Pull request by hadrien**
## Description

* This PR allows to run tests against multiple version of SQLAlchemy by using [tox](https://tox.readthedocs.io/en/latest/);
* Tests on different SQLAlchemy versions are run in CI in parallel: hence avoiding an execution time overhead;
* It tests against the highest 1.3 and 1.4 versions as 1.4 [SQLAlchemy 1.4 comes with major changes](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html);
* Out of many:
  * `asyncio` support
  * ORM Query is internally unified with select, update, delete; 2.0 style execution available
  * ... 

## Related JIRA issues

* [DIA-XXXXX]

## Checklist

- [x] Follows [Commit Convention] and [Code Review guidelines] 
- [x] Relevant labels set 
- [x] Empty sections removed
- [x] [Draft PR] for WIP
- [x] Requested from and notified to a team

[Commit Convention]: https://www.notion.so/godialogue/Commit-Convention-84fd9a4c149e48c998d760f1c9176df0
[Code Review guidelines]: https://www.notion.so/godialogue/Code-Review-c5f3fcd185ca49aca73ade497c398fe9
[Draft PR]: https://github.blog/2019-02-14-introducing-draft-pull-requests

### CODE REVIEW

**Review by mbelang — APPROVED** [review]
LGTM but have you consider using CircleCI [matrix](https://circleci.com/blog/circleci-matrix-jobs/)?

**Comment by hadrien** [comment]
> LGTM but have you consider using CircleCI [matrix](https://circleci.com/blog/circleci-matrix-jobs/)?

Yes. tox can run locally.

**Comment by hadrien** [comment]
main reason why I used it.

**Comment by hadrien** [comment]
🤔  I should probably update the readme.

**Comment by hadrien** [comment]
> 🤔 I should probably update the readme.

Actually, there is no developer doc at the moment, so this is the scope of another PR

**Comment by mbelang** [comment]
> > LGTM but have you consider using CircleCI [matrix](https://circleci.com/blog/circleci-matrix-jobs/)?
> 
> Yes. but, tox can be run locally as opposed to CCI matrix IIUC.

that was not my point. I was talking about CircleCi Matrix to have more beautiful pipeline lol

**Comment by hadrien** [comment]
> that was not my point. I was talking about CircleCi Matrix to have more beautiful pipeline lol

Sorry, I did not understand your point.

**Comment by hadrien** [comment]
-> #26

**Comment by hadrien** [comment]
ok i did not understand cci matrix 😬

**Pull request merged**
